### ISSUE TITLE
error compiling for M5Stack

### ISSUE THREAD

**Issue by Nep-Soundfont** [Pylo/MCreatorLinkArduino#3]
the library is not working with my new M5Stack when i upload the slightly modified bare minimum sketch. below is the errors

In file included from C:\Users\NEPSOU~1\AppData\Local\Temp\arduino_modified_sketch_721875\BareMinimum2.ino:2:0:

C:\Users\Nep Soundfont\Documents\Arduino\libraries\MCreator_Link\src/MCreatorLink.h:44:37: error: 'SERIAL_PORT_MONITOR' was not declared in this scope

     void setup(Stream &serial_ref = SERIAL_PORT_MONITOR, String deviceName = BOARD);

                                     ^
/*Duplicate libraries:
Multiple libraries were found for "SD.h"
 Used: C:\Users\Nep
 Not used: C:\Program
Multiple libraries were found for "WiFiClient.h"
 Used: C:\Users\Nep
 Not used: C:\Program
*/
exit status 1
Error compiling for board M5Stack-Core-ESP32.

**Comment by KlemenDEV** [comment]
Each Arduino device should define SERIAL_PORT_MONITOR define so this seems like a board code problem.

Try adding this in the code to overcome the issue:
```
#define SERIAL_PORT_MONITOR Serial
```

**Comment by Nep-Soundfont** [comment]
same error,  the second error refers to MCreatorLink.h which was included into the project as an IDE library, and the code is as follows: 
![image](https://user-images.githubusercontent.com/50643487/74093320-888ce280-4a8d-11ea-8d8d-17bde507f48a.png)

**Comment by KlemenDEV** [comment]
There are two options then:

1.  Ask developer of M5Stack to add SERIAL_PORT_MONITOR definition to the board definition which should be defined already
2. Edit MCreatorLink.h and change

``` 
void setup(Stream &serial_ref = SERIAL_PORT_MONITOR, String deviceName = BOARD);
``` 

to

``` 
void setup(Stream &serial_ref = Serial, String deviceName = BOARD);
```

**Comment by Nep-Soundfont** [comment]
another error, referring to MCreatorLink.cpp on line 79
C:\Users\Nep Soundfont\Documents\Arduino\libraries\MCreator_Link\src\MCreatorLink.cpp: In member function 'void MCreatorLinkImpl::loop()':

C:\Users\Nep Soundfont\Documents\Arduino\libraries\MCreator_Link\src\MCreatorLink.cpp:79:29: error: 'analogWrite' was not declared in this scope

**Comment by Nep-Soundfont** [comment]
ok, i fixed the error by replacing the analogwrite with serial println, code uploads, but the board wont appear in the link menu

**Comment by Dukeasas** [comment]
having the same issue

> ok, i fixed the error by replacing the analogwrite with serial println, code uploads, but the board wont appear in the link menu
